// import { Book, Library, ProfessorUser, StudentUser, } from "./library"

// const bib = new Library()
// const estudante = new StudentUser("Rafael")
// const professor = new ProfessorUser("Armando")

// bib.addBook(new Book("Livro1", "Fernando"))
// bib.addBook(new Book("Livro2", "Fernando"))
// bib.addBook(new Book("Livro3", "Fernando"))
// bib.addBook(new Book("Livro4", "Fernando"))
// bib.addBook(new Book("Livro5", "Fernando"))
// bib.addBook(new Book("Livro6", "Fernando"))
// bib.addBook(new Book("Livro7", "Fernando"))

// bib.addUser(estudante)
// bib.addUser(professor)

// professor.lendBook(bib.books[0])
// professor.lendBook(bib.books[1])
// professor.lendBook(bib.books[2])
// professor.lendBook(bib.books[3])
// professor.lendBook(bib.books[4])
// professor.lendBook(bib.books[5])
// professor.lendBook(bib.books[6])
// estudante.lendBook(bib.books[0])
// estudante.lendBook(bib.books[1])
// estudante.lendBook(bib.books[1])
// estudante.lendBook(bib.books[3])
// estudante.lendBook(bib.books[4])
// estudante.lendBook(bib.books[5])
// estudante.lendBook(bib.books[5])

// console.log(bib.books[0].emprestado)
// console.log(estudante.userName)
// console.log(professor.maxBooks)
// console.log(estudante.countBooks())
// console.log(professor.countBooks())
// console.log(bib.listBookLent())